@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TutorPro *-right-> "1" UniquePersonList
TutorPro *-up-> "1" UniqueTagList
TutorPro *-down-> "*" Reminder

UniqueTagList -right-> Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address

Person <|-right- Student
Student *--> Level
Student *--> "*" Subject
Person <|-right- Parent

Reminder <|-down- Event
Schedule -left-> Reminder
Schedule *--> "*" Event
@enduml
